# Отказоустойчивая загрузка с получением результата в JSON

Необходимо улучшить решение из предыдущей задачи <info:task/promise-errors-as-results>. Сейчас нам надо не просто вызвать `fetch`, но и загрузить JSON-объекты из указанных ссылок.

Как можно это сделать:

```js run
let urls = [
  'https://api.github.com/users/iliakan',
  'https://api.github.com/users/remy',
  'https://api.github.com/users/jeresig'
];

// выполнить запросы
Promise.all(urls.map(url => fetch(url)))
  // обработать каждый ответ, используя response.json()
  .then(responses => Promise.all(
    responses.map(r => r.json())
  ))
  // показать имя каждого пользователя
  .then(users => {  // (*)
    for(let user of users) {
      alert(user.name);
    }
  });
```

Проблема - если любой из запросов выполнится с ошибкой, то `Promise.all` вернёт эту ошибку и мы потеряем результаты со всех других запросов. Поэтому код, приведённых выше, не является отказоустойчивым, как и в предыдущей задаче.

Измените код так, чтобы массив в строке `(*)` включал бы в себя обработанный JSON для успешно выполненных запросов и ошибки для ошибочных.

Обратите внимание, что ошибки могут быть как при загрузке ссылки в `fetch` (если запрос не выполнился), так и в `response.json()` (если ответ содержит некорректный JSON). В обоих случаях ошибки должны быть элементами в объекте с результатами.

В песочнице есть оба этих случая.
